name: CI/CD

name: CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd main
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd main
          pytest -q

      - name: Upload pytest logs (artifact)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs
          path: main/.pytest_cache

  build_and_publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Diagnostics: print env
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}"
          echo "GITHUB_ACTOR=${{ github.actor }}"
          echo "Runner: $RUNNER_OS $RUNNER_TEMP"
          echo "Tag to push: ghcr.io/${{ github.repository_owner }}/flask-lab-project:latest"

      - name: Build image (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./main
          push: false
          tags: flask-lab-project:ci-latest

      - name: Image metadata
        run: |
          echo "Pushed image to ghcr.io/${{ github.repository_owner }}/flask-lab-project:latest"
