name: CI/CD

name: CI Diagnostic

on:
  push:
    branches: [ main ]

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print environment
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}"
          echo "GITHUB_ACTOR=${{ github.actor }}"
          python --version || echo 'python not found'
