name: CI/CD

name: CI Smoke Test

on:
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "CI smoke test: hello"
          echo "Repo: $GITHUB_REPOSITORY"
